### PR TITLE
Fixes the exception for models with threshold pressures.

### LINKED ISSUE #589: parallel flow_mpi crashes when thresholdPressures are used
Currently flow_mpi does not run for Norne as it uses the threshold pressure of the whole grid (as specified in the eclipse file) while the grid in the simulation only resembles a part of the grid. This crashes with
```
Program threw an exception: [/home/mblatt/DUNE-test/opm-autodiff/opm/autodiff/BlackoilModelBase_impl.hpp:383] Illegal size of threshold_pressures input ( 153924 ), must be equal to number of faces + nncs ( 78316 + 0 ).
```

The problem might have been produced when refactoring `flow.cpp` and `flow_mpi.cpp`. Currently the threshold pressures are computed within `FlowMainBase::setupState` which works on the whole grid.  Later the grid and the data is distributed during `distributeData`, which does not and never did distribute the threshold pressures.

As it worked somewhen my guess is that previously the thresholdPressures were setup after loadbalancing the grid and the data. If that is still possible I would love to resort to this behaviour:
```
setupSate();
distributeData();
setupLocalState(); // read threshold pressure with the distributed grid.
```

To me it seems like all the functions (`thresholdPressures`, `thresholdPressuresNNC`, and `computeMaxDp`) should work if the grid resembles only a part of the one defined in the eclipse file. As I might be missing something, I would appreciate it if someone would confirm this few.

### PR DESCRIPTION
**Pull request by blattms**
Since the support for threshold pressures running Norne with
flow_mpi aborted error messages like
```
Program threw an exception: [/home/mblatt/DUNE-test/opm-autodiff/opm/autodiff/BlackoilModelBase_impl.hpp:383] Illegal size of threshold_pressures input ( 153924 ), must be equal to number of faces + nncs ( 78316 + 0 ).
```
This commit now distributes the threshold pressures (if present) just like the rest
of the model properties and Norne does not abort here any more.

Please note:
1. If there are NNCs flow_mpi will abort with an error.
2. We might want to resort to reading and calculating the threshold pressure
  (and maybe other properties) on distributed grids instead of using communication.

Fixes #589

### CODE REVIEW

**Comment by blattms** [comment]
Please note that I have not yet run the whole Norne model but only confirmed that the simulator is able to the first timesteps of Norne in parallel

File: opm/autodiff/RedistributeDataHandles.hpp [hunk 1]
```diff
@@ -387,11 +460,30 @@ void distributeGridAndData( Dune::CpGrid& grid,
...
+    std::vector<double> distributed_pressures;
+
+    if( !threshold_pressures.empty() ) // Might be empty if not specified
+    {
+        if( threshold_pressures.size() !=
+            static_cast<std::size_t>(UgGridHelpers::numFaces(global_grid)) )
+        {
+            OPM_THROW(std::runtime_error, "NNCs not yet supported for parallel runs. "
+                      << UgGridHelpers::numFaces(grid) << " faces but " <<
+                      threshold_pressures.size()<<" pressure values");
```
Comment (atgeirr) [inline opm/autodiff/RedistributeDataHandles.hpp]: Minor detail: this error message will be confusing, better to say "threshold pressure values" instead of "pressure values".

File: opm/autodiff/RedistributeDataHandles.hpp [hunk 2]
```diff
@@ -40,12 +40,84 @@ inline void distributeGridAndData( Grid& ,
...
                                    std::shared_ptr<BlackoilPropsAdFromDeck::MaterialLawManager>&,
+                                   std::vector<double>&,
                                    boost::any& ,
                                    const bool )
 {
 }
 
 #if HAVE_DUNE_CORNERPOINT && HAVE_MPI
+/// \brief a data handle to distribute the threshold pressures
+class ThresholdPressureDataHandle
```
Comment (atgeirr) [inline opm/autodiff/RedistributeDataHandles.hpp]: This class seems to me to work on a cell level, and then for each cell communicating the threshold pressures for each adjacent face. That would communicate almost twice as many values as necessary. Could that be reduced by communicating on faces instead?

File: opm/autodiff/RedistributeDataHandles.hpp (hunk 1 above)
Comment (blattms) [inline opm/autodiff/RedistributeDataHandles.hpp]: On Thu, Feb 18, 2016 at 09:10:29AM -0800, Atgeirr Flø Rasmussen wrote:
> Minor detail: this error message will be confusing, better to say "threshold pressure values" instead of "pressure values".

Fixed.

File: opm/autodiff/RedistributeDataHandles.hpp (hunk 2 above)
Comment (blattms) [inline opm/autodiff/RedistributeDataHandles.hpp]: On Thu, Feb 18, 2016 at 09:14:23AM -0800, Atgeirr Flø Rasmussen wrote:
> This class seems to me to work on a cell level, and then for each cell communicating the threshold pressures for each adjacent face. That would communicate almost twice as many values as necessary. Could that be reduced by communicating on faces instead?
> 

Yes it does and yes it could with some work effort.

As most of the communication takes place on cells, one
can currently only communicate on cells. Adding communication to the
interfaces is possible (at least for newer DUNE versions), but we have
to store an additional communication pattern. Maybe we could throw that
away after this communication step, though.

Comment (atgeirr) [inline opm/autodiff/RedistributeDataHandles.hpp]: If that communication capability is not needed elsewhere (linear solver for example) it seems a little overkill to implement it just for this, so it's ok to keep it as is.

**Comment by atgeirr** [comment]
I'll merge the PR, thanks for the fix!

**Comment by blattms** [comment]
You are welcome. Thanks for the fast merge
